kind: source
spec:
  name: vault
  path: alyragab/CloudQuery-Vault
  version: v1.0.0
  destinations: ["sqlite"]
  tables: ["vault"]
  spec:
---
kind: destination
spec:
  name: sqlite
  path: cloudquery/sqlite
  version: v1.2.3
  spec:
    connection_string: ./sqlite.sql
