name: Build

on:
  pull_request:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses:  actions/checkout@v2
    - name: Go version
      uses: actions/setup-go@v2
      with:
        go-version: '1.15'
    - name: Install dependencies
      run: |
        go version
    - name: Go build
      run: |
         go build -o cq-source-CloudQuery-Vault main.go