name: goreleaser
on:
  push:
    branches:
      - main

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Run GoReleaser Dry-Run
        uses: goreleaser/goreleaser-action@v3
        with:
          version: latest
          args: release --rm-dist --skip-validate --skip-publish --skip-sign
      - uses: release-drafter/release-drafter@v5.17.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          version: latest
          args: release --rm-dist --skip-sign
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
